### ISSUE TITLE
fix search bar for mobile versions

### ISSUE THREAD

**Issue by 2fd** [decentraland/events#55]
|                   |                   |
|-----------|-----------|
| ![IMG_9593](https://user-images.githubusercontent.com/208789/162467752-45610ca1-1a06-4d5f-9667-688e18cc88b3.jpg) | ![IMG_9594](https://user-images.githubusercontent.com/208789/162467802-2e620ee6-3832-49df-af96-453be19ba2c2.jpg) |

**Comment by 1219aks** [comment]
Can you assign this to me please?
