### ISSUE TITLE
Filter event by time

### ISSUE THREAD

**Issue by 2fd** [decentraland/events#62]
Reference: https://www.figma.com/file/VceN562hgOF0bRhg5t32Vz/Events-filtering?node-id=231%3A1132

<img width="295" alt="Screen Shot 2022-04-10 at 00 15 17" src="https://user-images.githubusercontent.com/208789/162599813-ecc82443-fe7b-45bc-ab5c-1d642c70de9c.png">

- add A/B testing with feature-flags (create a new one)
- time rage should be the same used to show the event time

examples: 
- https://decentraland.litebox.ai/openings?experienceFrom=0&experienceTo=20
- https://github.com/nicolasgalano/talent-hub/tree/develop

**Comment by braianj** [comment]
Related to PR #142
